apiVersion: v1
kind: Service
metadata:
  name: lab4-service
  labels:
    app: lab4
spec:
  selector:
    app: lab4
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer